### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by Wisesaturn** [Wisesaturn/blog#2]
- [x] #5
- [x] #9
   - [x] #14
   - [x] 메인 페이지 프로필
      - [x] 반응형에 맞게 더 수정 필요
- [x] #11
- [x] #3
- [x]  Header Effect 추가
- [x]  Footer Navigation 추가 
- [x] #16
- [x] #19
- [x]  Google Search Console 추가
(sitemap.xml / robots.txt #20)
- [x] #20
- [x] 로딩 UI
- [x] #6
- [x] SSR 로딩 속도 개선 -> 노션 API에만 의존하지 않고 firebase DB 사용
- [x] 2차 SSR 로딩 속도 개선 -> Firestore를 이용하여 업데이트 조건에 따라 notion에 요청 후 firebase DB에 저장
- [x] 이미지 렌더링 최적화 (올릴 때 webp)
- [x] #35
- [x] Safari 이슈 (Header Animation 등)
- [x] #31
- [x] #24
- [x] #42
- [x] #44
- [x] #46  
- [x] #50
- [x] #53
